In [16]:
import pandas as pd

holdings_df = pd.read_csv('Asset_Manager_Holdings.csv')
#holdings_df

In [17]:
companies_df = pd.read_csv('Company_Filings.csv')

In [20]:
companies_df['name'] = companies_df['name'].str.strip().str.upper()
companies_df['form10KUrls'] = companies_df['form10KUrls'].str.replace('\\', '/')
companies_df.to_csv('Companies.csv', index=False)
companies_df

,cusip6,cik,name,cusip,form10KUrls,ticker
0,23135,1018724,AMAZON,23135106,data/form10k-sample/0001018724-23-000004.pdf,AMZN
1,67066,1045810,NVIDIA CORPORATION,067066G104,data/form10k-sample/0001045810-23-000017.pdf,NVDA
2,378331,1490054,APPLE INC,3783310,data/form10k-sample/0001096906-23-001489.pdf,AAPL
3,163917,1633917,PAYPAL,1633917,data/form10k-sample/0001633917-23-000033.pdf,PYPL
4,378339,320193,APPLE INC,37833950,data/form10k-sample/0000320193-23-000106.pdf,INTC
5,458140,50863,INTEL CORP,458140950,data/form10k-sample/000050863-23-000006.pdf,INTL
6,268748,5272,AMERICAN INTL GROUP,26874784,data/form10k-sample/00005272-23-000007.pdf,AIG
7,69331,75488,PG&E CORP,069331C908,data/form10k-sample/0001004980-23-000029.pdf,PCG
8,580135,63908,MCDONALDS CORP,580135101,data/form10k-sample/000063908-23-000012.pdf,MCD
9,594918,789019,MICROSOFT CORP,594918954,data/form10k-sample/0000950170-23-035122.pdf,MSFT

In [21]:
aligned_holdings_df = holdings_df.merge(companies_df[['cusip', 'name']], on='cusip', how="left")
aligned_holdings_df['companyName'] = aligned_holdings_df['name'].fillna(aligned_holdings_df['companyName'])
aligned_holdings_df.drop(columns=['name'], inplace=True)
aligned_holdings_df.to_csv('Asset_Holdings.csv', index=False)
aligned_holdings_df

,source,managerCik,managerName,reportCalendarOrQuarter,cusip6,cusip,companyName,position_status,ticker,Value,shares,share_value
0,https://sec.gov/Archives/edgar/data/1109448/00...,1109448,ALLIANCEBERNSTEIN L.P.,9/30/2023,23135,23135106,AMAZON,current,AMZN,6.360000e+09,50065439,127.033741
1,https://sec.gov/Archives/edgar/data/1109448/00...,1109448,ALLIANCEBERNSTEIN L.P.,9/30/2023,37833,37833100,APPLE INC,current,AAPL,4.820000e+09,28143032,171.267971
2,https://sec.gov/Archives/edgar/data/1109448/00...,1109448,ALLIANCEBERNSTEIN L.P.,9/30/2023,458140,458140100,INTEL CORP,current,INTC,2.040000e+08,5735993,35.564897
3,https://sec.gov/Archives/edgar/data/1109448/00...,1109448,ALLIANCEBERNSTEIN L.P.,9/30/2023,580135,580135101,MCDONALDS CORP,current,MCD,3.170000e+08,1201960,263.735898
4,https://sec.gov/Archives/edgar/data/1109448/00...,1109448,ALLIANCEBERNSTEIN L.P.,9/30/2023,594918,594918104,MICROSOFT CORP,current,MSFT,1.470000e+10,46541943,315.844141
...,...,...,...,...,...,...,...,...,...,...,...,...
115,https://sec.gov/Archives/edgar/data/72971/0000...,72971,WELLS FARGO & COMPANY/MN,9/30/2023,580135,580135101,MCDONALDS CORP,current,MCD,2.110000e+09,8002862,263.655677
116,https://sec.gov/Archives/edgar/data/72971/0000...,72971,WELLS FARGO & COMPANY/MN,9/30/2023,594918,594918104,MICROSOFT CORP,current,MSFT,1.130000e+10,35862559,315.091848
117,https://sec.gov/Archives/edgar/data/72971/0000...,72971,WELLS FARGO & COMPANY/MN,9/30/2023,67066G,67066G104,NVIDIA CORPORATION,current,NVDA,2.210000e+09,5084980,434.613312
118,https://sec.gov/Archives/edgar/data/72971/0000...,72971,WELLS FARGO & COMPANY/MN,9/30/2023,70450Y,70450Y103,PAYPAL HLDGS INC,current,PYPL,2.130000e+08,3647865,58.390319
119,https://sec.gov/Archives/edgar/data/72971/0000...,72971,WELLS FARGO & COMPANY/MN,9/30/2023,69331C,69331C108,PG&E CORP,current,PCG,1.861900e+07,1154308,16.130006